module.exports.CMSG_NICKNAME = 'client.nickname'
module.exports.CMSG_GAME_STATE_ACK = 'client.game.state.ack'
module.exports.CMSG_GAME_ANSWER = 'client.game.answer'
module.exports.CMSG_CHAT_MESSAGE = 'client.chat.message'

module.exports.SMSG_NICKNAME_ACK = 'server.nickname.ack'
module.exports.SMSG_PLAYERS_LIST = 'server.players.list'
module.exports.SMSG_GAME_STATE_UPDATE = 'server.game.state.update'
module.exports.SMSG_GAME_QUESTION = 'server.game.question'
module.exports.SMSG_PLAYERS_SCORE = 'server.players.score'
module.exports.SMSG_GAME_PLAYERS = 'server.game.players'
module.exports.SMSG_CHAT_MESSAGE = 'server.chat.message'
module.exports.SMSG_PLAYER_JOIN = 'server.player.join'
module.exports.SMSG_PLAYER_LEAVE = 'server.player.leave'